spring:
  data:
    mongodb:
      database: "life-at-a-glance"
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ""
            clientSecret: ""
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

security:
  oauth2:
    tokenSecret: ""
    tokenExpirationMs: 864000000
    authorizedRedirectUris:
      - "{baseUrl}/oauth2/redirect"
